In [1]:
import pandas as pd

In [2]:
import numpy as np

In [4]:
from numpy import array
a= ([[4,7,9],[3,2,5]])
print(a)

[[4, 7, 9], [3, 2, 5]]


In [6]:
X = array([[3,1,6],[3,9,6]])
Y = array([[7,4,9],[8,2,5]])
print(X+Y)

[[10  5 15]
 [11 11 11]]


In [7]:
X = array([[2,1,7],[4,2,6]])
Y = array([[8,4,2],[1,2,5]])
print(X-Y)

[[-6 -3  5]
 [ 3  0  1]]


In [9]:
X = array([[9,8,7],[4,5,6]])
Y = array([[3,4,2],[1,2,3]])
print(X*Y)

[[27 32 14]
 [ 4 10 18]]


In [10]:
X = array([[1,2,3],[4,5,6]])
Y = array([[7,8,9],[1,2,3]])
print(X/Y)

[[0.14285714 0.25       0.33333333]
 [4.         2.5        2.        ]]


In [21]:
from numpy import *
x = array([['Sun',20,16,23,12],['Mon',29,11,20,22],['Tue',24,26,28,22],['Wed',13,15,17,19],['Thu',10,13,26,12],['Fri',24,15,23,18],['Sat',23,14,28,22]])
print(x)
# s= reshape(x,(7,5))

[['Sun' '20' '16' '23' '12']
 ['Mon' '29' '11' '20' '22']
 ['Tue' '24' '26' '28' '22']
 ['Wed' '13' '15' '17' '19']
 ['Thu' '10' '13' '26' '12']
 ['Fri' '24' '15' '23' '18']
 ['Sat' '23' '14' '28' '22']]


In [22]:
print(x[3])

['Wed' '13' '15' '17' '19']


In [23]:
print(x[2][2])

26


In [28]:
from numpy import *
a = array([['Sun',20,16,23,12],['Mon',29,11,20,22],['Tue',24,26,28,22],['Wed',13,15,17,19],['Thu',10,13,26,12],['Fri',24,15,23,18],['Sat',23,14,28,22]])

b= append(a,[['Avg',12,13,14,15]],0)
print(b)

[['Sun' '20' '16' '23' '12']
 ['Mon' '29' '11' '20' '22']
 ['Tue' '24' '26' '28' '22']
 ['Wed' '13' '15' '17' '19']
 ['Thu' '10' '13' '26' '12']
 ['Fri' '24' '15' '23' '18']
 ['Sat' '23' '14' '28' '22']
 ['Avg' '12' '13' '14' '15']]


In [26]:
from numpy import *
p = array([['Sun',20,16,23,12],['Mon',29,11,20,22],['Tue',24,26,28,22],['Wed',13,15,17,19],['Thu',10,13,26,12],['Fri',24,15,23,18],['Sat',23,14,28,22]])

q = insert(p,[3],[[5],[8],[3],[7],[5],[1],[2]],1)
print(q)

[['Sun' '20' '16' '5' '23' '12']
 ['Mon' '29' '11' '8' '20' '22']
 ['Tue' '24' '26' '3' '28' '22']
 ['Wed' '13' '15' '7' '17' '19']
 ['Thu' '10' '13' '5' '26' '12']
 ['Fri' '24' '15' '1' '23' '18']
 ['Sat' '23' '14' '2' '28' '22']]
